const devices = {
    "PC de bureau": [
      "Processeur",
      "Carte mère",
      "RAM",
      "Carte graphique",
      "Stockage (HDD/SSD)",
      "Alimentation",
      "Boîtier",
      "Système d’exploitation (windows 10/windows 11/windows xp/windows 7/Linux/Mac)",
    ],
    "PC portable": [
      "Processeur",
      "Carte mère",
      "RAM",
      "Carte graphique",
      "Stockage (HDD/SSD)",
      "Batterie",
      "Écran",
      "Clavier",
      "Touchpad",
      "Système d’exploitation (windows 10/windows 11/windows xp/windows 7/Linux/Mac)",

    ],
    "Station de travail": [
      "Processeur hautes performances",
      "Carte mère",
      "RAM",
      "Carte graphique professionnelle",
      "Stockage NVMe",
      "Alimentation robuste",
      "Refroidissement avancé",
    ],
    Serveur: [
      "Processeur multi-cœurs",
      "Carte mère serveur",
      "RAM ECC",
      "Baies de stockage RAID",
      "Alimentation redondante",
      "Carte réseau 10Gbps",
    ],
    Écran: [
      "Taille",
      "Résolution",
      "Taux de rafraîchissement",
      "Connectique (HDMI, DisplayPort, VGA)",
      "Technologie (IPS, TN, OLED)",
    ],
    Clavier: [
      "Type (mécanique/membrane)",
      "Disposition (AZERTY/QWERTY)",
      "Rétroéclairage",
      "Connectique (USB/Sans fil)",
    ],
    Souris: [
      "Type (optique/laser)",
      "DPI",
      "Boutons programmables",
      "Connexion (filaire/sans fil)",
    ],
    Imprimante: [
          "Type (laser/jet d'encre)",
          "(Couleur/Monochrome)",
          "Résolution d'impression",
          "Connectique (USB/Wi-Fi)"
    ],    

    Scanner: [
      "Type (à plat/feuille)",
      "Résolution",
      "Vitesse de numérisation",
      "Connectique",
    ],
    Webcam: ["Résolution", "Framerate", "Micro intégré", "Angle de vision"],
    "Disque dur externe": [
      "Capacité",
      "Type (HDD/SSD)",
      "Connectique (USB 3.0/USB-C)",
    ],
    "Clé USB": ["Capacité", "Type (USB 2.0/3.0/3.1)"],
    "Carte mémoire": [
      "Type (SD, microSD, CompactFlash)",
      "Capacité",
      "Classe de vitesse",
    ],
    NAS: [
      "Baies de stockage",
      "Processeur",
      "RAM",
      "Connectivité (Ethernet, USB)",
    ],
    Routeur: [
      "Norme Wi-Fi (802.11ac/ax)",
      "Bande passante",
      "Nombre de ports LAN/WAN",
      "Sécurité (WPA2, WPA3)",
    ],
    Switch: [
      "Nombre de ports",
      "Débit (1Gbps/10Gbps)",
      "Gestion (non-manageable/manageable)",
    ],
    Modem: ["Compatibilité (ADSL, Fibre, 4G)", "Ports Ethernet"],
    "Point d’accès Wi-Fi": ["Norme Wi-Fi", "Bande passante", "Sécurité"],
    Smartphone: [
      "Processeur",
      "RAM",
      "Stockage",
      "Écran",
      "Batterie",
      "Caméras",
      "Connectivité (5G, Wi-Fi, Bluetooth, NFC)",
    ],
    Tablette: [
      "Processeur",
      "RAM",
      "Stockage",
      "Écran",
      "Batterie",
      "Stylet",
      "Connectivité",
    ],
    "Montre connectée": [
      "Écran",
      "Capteurs (cardio, GPS)",
      "Autonomie",
      "Connectivité (Bluetooth, Wi-Fi)",
    ],
    Vidéoprojecteur: [
      "Résolution",
      "Luminosité",
      "Contraste",
      "Connectique (HDMI, VGA)",
    ],
    Onduleur: ["Puissance (VA/W)", "Autonomie", "Nombre de prises"],
    "Casque audio": [
      "Type (filaire/sans fil)",
      "Réduction de bruit",
      "Autonomie (si sans fil)",
    ],
  };

  export default devices;